#  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: backendlogs
spec:
  selector:
    matchLabels:
      app: backendlogs
  replicas: 1
  template:
    metadata:
      labels:
        app: backendlogs
    spec:
      containers:
      - name: backendlogs
        imagePullPolicy: Always
        image: <enter your doceker image name (backend logs):version here>
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: DB_URL
          value: DB_URL
        - name: RABBITMQ_URI
          value: RABBITMQ_URI
        - name: PYTHONUNBUFFERED
          value: "TRUE"
---