#  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: frontendlogs
spec:
  selector:
    matchLabels:
      app: frontendlogs
  replicas: 1
  template:
    metadata:
      labels:
        app: frontendlogs
    spec:
      containers:
      - name: frontendlogs
        imagePullPolicy: Always
        image: <enter your doceker image name (frontend logs):version here>
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: RABBITMQ_HOST
          value: rabbitmq
        - name: PYTHONUNBUFFERED
          value: "TRUE"
---