# This is a basic workflow to help you get started with Actions

name: Deploy to Google App Engine

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    name: Deploying to Google Cloud
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Secrets
      run: |
        cp example.app.yaml app.yaml
        sed -i 's/DB_URL: ""/DB_URL: "${{ secrets.DB_URL }}"/' app.yaml   
        sed -i 's/NYT_API_KEY: ""/NYT_API_KEY: "${{ secrets.NYT_API_KEY }}"/' app.yaml
        sed -i 's/GOOGLE_API_KEY: ""/GOOGLE_API_KEY: "${{ secrets.GOOGLE_API_KEY }}"/' app.yaml

    - name: Deploy to App Engine
      id: deploy
      uses: google-github-actions/deploy-appengine@v0.2.0
      with:
        deliverables: app.yaml
        version: 20220418t100546
        project_id: ${{ secrets.GCP_PROJECT }}
        credentials: ${{ secrets.GCP_CREDENTIALS }}

    - name: Test
      run: curl "${{ steps.deploy.outputs.url }}/api/2020/04/03"
